"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const CriarUsuarioController_1 = require("./controllers/usuario/CriarUsuarioController");
const AuthUsuarioController_1 = require("./controllers/usuario/AuthUsuarioController");
const CriarFisioterapeutaController_1 = require("./controllers/fisioterapeuta/CriarFisioterapeutaController");
const CriarPacienteController_1 = require("./controllers/paciente/CriarPacienteController");
const CriarOrientacaoController_1 = require("./controllers/orientacao/CriarOrientacaoController");
const CriarUrinaController_1 = require("./controllers/urina/CriarUrinaController");
const CriarBebidaController_1 = require("./controllers/bebida/CriarBebidaController");
const DetalhesPacienteController_1 = require("./controllers/paciente/DetalhesPacienteController");
const DetalhesFisioterapeutaController_1 = require("./controllers/fisioterapeuta/DetalhesFisioterapeutaController");
const ListarFisioterapeutaController_1 = require("./controllers/fisioterapeuta/ListarFisioterapeutaController");
const ListarOrientacaoController_1 = require("./controllers/orientacao/ListarOrientacaoController");
const ListarUrinaController_1 = require("./controllers/urina/ListarUrinaController");
const ListarBebidaController_1 = require("./controllers/bebida/ListarBebidaController");
const DeletarUrinaController_1 = require("./controllers/urina/DeletarUrinaController");
const DeletarBebidaController_1 = require("./controllers/bebida/DeletarBebidaController");
const DeletarOrientacaoController_1 = require("./controllers/orientacao/DeletarOrientacaoController");
const AtualizarBebidaController_1 = require("./controllers/bebida/AtualizarBebidaController");
const AtualizarUrinaController_1 = require("./controllers/urina/AtualizarUrinaController");
const AtualizarOrientacaoController_1 = require("./controllers/orientacao/AtualizarOrientacaoController");
const AtualizarPacienteController_1 = require("./controllers/paciente/AtualizarPacienteController");
const AtualizarStatusPacienteController_1 = require("./controllers/paciente/AtualizarStatusPacienteController");
const DetalhesUsuarioController_1 = require("./controllers/usuario/DetalhesUsuarioController");
const AtualizarUsuarioController_1 = require("./controllers/usuario/AtualizarUsuarioController");
const AtualizarFisioterapeutaController_1 = require("./controllers/fisioterapeuta/AtualizarFisioterapeutaController");
const DetalhesUrinaController_1 = require("./controllers/urina/DetalhesUrinaController");
const DetalhesBebidaController_1 = require("../src/controllers/bebida/DetalhesBebidaController");
const BuscarUrinaController_1 = require("./controllers/urina/BuscarUrinaController");
const authUsuario_1 = require("./middlewares/authUsuario");
const authUsuario_2 = require("./middlewares/authUsuario");
const authUsuario_3 = require("./middlewares/authUsuario");
const BuscarBebidaController_1 = require("./controllers/bebida/BuscarBebidaController");
const MeusPacientesController_1 = require("./controllers/fisioterapeuta/MeusPacientesController");
const BuscarPacienteController_1 = require("./controllers/fisioterapeuta/BuscarPacienteController");
const BuscarRegistrosController_1 = require("./controllers/fisioterapeuta/BuscarRegistrosController");
const BuscarOrientacoesController_1 = require("./controllers/fisioterapeuta/BuscarOrientacoesController");
const DetalhesOrientacaoController_1 = require("./controllers/orientacao/DetalhesOrientacaoController");
const MarcarOrientacaoLidaController_1 = require("./controllers/orientacao/MarcarOrientacaoLidaController");
const recuperar_senha_1 = __importDefault(require("./utils/recuperar-senha"));
const nova_senha_1 = __importDefault(require("./utils/nova-senha"));
const BuscarRegistrosParamsController_1 = require("./controllers/fisioterapeuta/BuscarRegistrosParamsController");
const TrocarSenhaController_1 = require("./controllers/usuario/TrocarSenhaController");
const router = (0, express_1.Router)();
exports.router = router;
//ROTAS SEM PROTEÇÃO (USUÁRIOS DESLOGADOS)
router.post('/usuarios', new CriarUsuarioController_1.CriarUsuarioController().handle);
router.post('/login', new AuthUsuarioController_1.AuthUsuarioController().handle);
router.post('/fisioterapeuta', new CriarFisioterapeutaController_1.CriarFisioterapeutaController().handle);
router.post('/paciente', new CriarPacienteController_1.CriarPacienteController().handle);
router.get('/fisioterapeutas', new ListarFisioterapeutaController_1.ListarFisioterapeutaController().handle);
router.post('/recuperar-senha', recuperar_senha_1.default);
router.post('/nova-senha', nova_senha_1.default);
// ROTAS FISIOTERAPEUTA
router.post('/orientacoes', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new CriarOrientacaoController_1.CriarOrientacaoController().handle);
router.delete('/orientacoes/:orientacao_id', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new DeletarOrientacaoController_1.DeletarOrientacaoController().handle);
router.put('/orientacoes/:orientacao_id', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new AtualizarOrientacaoController_1.AtualizarOrientacaoController().handle);
router.get('/fisioterapeuta/detalhes', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new DetalhesFisioterapeutaController_1.DetalhesFisioterapeutaController().handle);
router.put('/fisioterapeuta', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new AtualizarFisioterapeutaController_1.AtualizarFisioterapeutaController().handle);
router.get('/fisioterapeuta/pacientes', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new MeusPacientesController_1.MeusPacientesController().handle);
router.get('/paciente/id', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new BuscarPacienteController_1.BuscarPacienteController().handle);
router.get('/registros/paciente', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new BuscarRegistrosController_1.BuscarRegistrosController().handle);
router.get('/registros/paciente/:paciente_id', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new BuscarRegistrosParamsController_1.BuscarRegistrosParamsController().handle);
router.get('/orientacoes', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new ListarOrientacaoController_1.ListarOrientacaoController().handle);
router.get('/orientacoes/paciente', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new BuscarOrientacoesController_1.BuscarOrientacoesController().handle);
router.put('/paciente/status/:paciente_id', authUsuario_1.authUsuario, authUsuario_2.protegeRotaFisioterapeuta, new AtualizarStatusPacienteController_1.AtualizarStatusPacienteController().handle);
//ROTAS NEUTRAS
router.get('/detalhes', authUsuario_1.authUsuario, new DetalhesUsuarioController_1.ListarUsuarioController().handle);
router.put('/usuario', authUsuario_1.authUsuario, new AtualizarUsuarioController_1.AtualizarUsuarioController().handle);
router.put('/trocar-senha', authUsuario_1.authUsuario, new TrocarSenhaController_1.TrocarSenhaController().handle);
// ROTAS PACIENTE --
router.get('/paciente/detalhes', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new DetalhesPacienteController_1.DetalhesPacienteController().handle);
router.put('/paciente', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new AtualizarPacienteController_1.AtualizarPacienteController().handle);
router.post('/urina', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new CriarUrinaController_1.CriarUrinaController().handle);
router.post('/bebida', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new CriarBebidaController_1.CriarBebidaController().handle);
router.get('/urinas', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new ListarUrinaController_1.ListarUrinaController().handle);
router.get('/urina/id', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new BuscarUrinaController_1.BuscarUrinaController().handle);
router.get('/urina/detalhes', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new DetalhesUrinaController_1.DetalhesUrinaController().handle);
router.get('/bebidas', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new ListarBebidaController_1.ListarBebidaController().handle);
router.get('/bebida/detalhes', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new DetalhesBebidaController_1.DetalhesBebidaController().handle);
router.get('/bebida/id', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new BuscarBebidaController_1.BuscarBebidaController().handle);
router.delete('/paciente/urinas', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new DeletarUrinaController_1.DeletarUrinaController().handle);
router.delete('/paciente/bebidas', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new DeletarBebidaController_1.DeletarBebidaController().handle);
router.put('/paciente/bebida/:bebida_id', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new AtualizarBebidaController_1.AtualizarBebidaController().handle);
router.put('/paciente/urina/:urina_id', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new AtualizarUrinaController_1.AtualizarUrinaController().handle);
router.get('/orientacoes/detalhes', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new DetalhesOrientacaoController_1.DetalhesOrientacaoController().handle);
router.put('/orientacoes/marcar/:orientacao_id', authUsuario_1.authUsuario, authUsuario_3.protegeRotaPaciente, new MarcarOrientacaoLidaController_1.MarcarOrientacaoLidaController().handle);
